server:
  port: 8083
spring:
  application:
    name: notification-service

info:
  application:
    name: ${spring.application.name}
    description: '@project.description@'
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'